<a href="https://colab.research.google.com/github/Jheyson-Dev/Big-Data/blob/main/Sesion4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importamos las librearia numpy de Python
import numpy as np

In [48]:
#Creamos un arreglo de una dimension
arreglo = np.array([1,2,3,9,8,7])
print(arreglo)

[1 2 3 9 8 7]


In [49]:
#hacemos referencia al nunero par "2" que esta en el indice 1
numero_par = arreglo[1]
print(numero_par)

2


In [ ]:
tablero =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(tablero)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Ejemplos de refecncia a elementos del arreglo bidimensional
n1 = tablero[0][0] # Referenia al elemento de la fila 0 y el elemento 0
print(n1)
n2 = tablero[3][2] # Referenia al elemento de la fila 3 y el elemento 2
print(n2)
n3 = tablero[2][2] # Referenia al elemento de la fila 2 y el elemento 2
print(n3)

1
12
9


**Propiedades principales de los arreglos**

In [ ]:
# Número de dimensiones

# Usamos la propiedad ndim para obtener la dimension d elos arreglos

print(arreglo.ndim)
print(tablero.ndim)

1
2


In [ ]:
# Propiedad Shape
# Nos devuelve el número de filas y columnas de un arreglo
print(arreglo.shape)
print(tablero.shape)

(3,)
(4, 3)


In [ ]:
# Propiedad size
# Nos devuelve el número total de elementos que tiene un arreglo sin importar las dimensiones
print(arreglo.size)
print(tablero.size)

3
12


In [ ]:
# Otras funciones útiles
# Creación de un tablero con 8 filas y 8 columnas con valores "0"

tabler_ceros = np.zeros([8,8], int)
print(tabler_ceros)

# Creación de un tablero con 8 filas y 8 columnas con valores "1"
tabler_unos = np.ones([8,8], int)
print(tabler_unos)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [ ]:
# Creacion de un tablero inicializado con un valor "x", para el ejemplo 10

tabler_x = np.full([8,8],10,int)
print(tabler_x)

[[10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10]]


In [ ]:
# Creacion d eun tablero inicializado con valores aleatorios

tablr_random = np.random.rand(3,3)
print(tablr_random)

[[0.33615661 0.31034273 0.55162224]
 [0.52651127 0.83537896 0.61706539]
 [0.71657708 0.54470105 0.9374296 ]]


In [43]:
# Creacion de un tabler inicialiado con numeros aleatorios delimitados entre un rango , para el ejemplo "1-10"

tablr_a = np.random.randint(1,200,size=(4,4))
print(tablr_a)


[[180  25 130 187]
 [ 27  25 171  82]
 [120 181 131 122]
 [ 99 141   4 185]]


In [44]:
# prompt: creame una funcion que en base que le de un numero me sume todos los elementos de esa fila este es mi arreglo tablr_a

import numpy as np
def sum_row(arr, row_num):
  if row_num >= arr.shape[0]:
      raise IndexError("La columna no existe")
  return np.sum(arr[row_num, :])

# Example usage

fila = int(input("inngrese la fila:"))
row_sum = sum_row(tablr_a, fila)
print(f"La suma de valores de la fila {fila} es: {row_sum}")


inngrese la fila:2
La suma de valores de la fila 2 es: 554


In [47]:
# prompt: quiero que me sumen todos los valores de una fila no importa cuantas filas tenga en arreglo pero lso resultados tienen que ser suma de la fila , ... hasta las filas que tenga el array

import numpy as np
def sum_all_rows(arr):
  row_sums = []
  for row_num in range(arr.shape[0]):
    row_sum = np.sum(arr[row_num, :])
    row_sums.append(row_sum)
  return row_sums

# Example usage

row_sums = sum_all_rows(tablr_a)
for i, row_sum in enumerate(row_sums):
  print(f"La suma de valores de la fila {i+1} es: {row_sum}")


La suma de valores de la fila 1 es: 522
La suma de valores de la fila 2 es: 305
La suma de valores de la fila 3 es: 554
La suma de valores de la fila 4 es: 429


In [54]:
# Redimensinamos el "arreglo" a una matriz de 3x2
# Propiedad reshape permite redimensionar una matriz o un vector siempre y cuando sean multiplos del numero total de elentos de la matriz

new_array= arreglo.reshape((3,2))
print(new_array)

[[1 2]
 [3 9]
 [8 7]]
