**Importar NumPy:**

In [1]:
import numpy as np

**1. Creación de Arrays:**

In [14]:
#Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.
array = np.array([2,3,4,5,6])
print(array)

[2 3 4 5 6]


In [6]:
#Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
new_array = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(new_array)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
array_zeros = np.zeros([2,4], int)
print(array_zeros)

[[0 0 0 0]
 [0 0 0 0]]


In [11]:
# Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.

array_ones = np.ones([3,2], int)
print(array_ones)

[[1 1]
 [1 1]
 [1 1]]


In [13]:
# Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.

array_random_0_10 = np.random.randint(0,10, size=(4,4))

print(array_random_0_10)

[[5 2 7 1]
 [2 4 4 5]
 [7 8 7 0]
 [0 9 3 9]]


**2. Acceso a Elementos:**

In [15]:
# Accede al tercer elemento del vector creado en el paso 1.
elemento_3 = array[2]

print(elemento_3)

4


In [16]:
#Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 2.
elemento_2 = new_array[1][1]
print(elemento_2)

8


**3. Propiedades de los Arrays:**

In [19]:
# Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 2.

print(new_array.ndim)

2


In [20]:
# Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.
print(new_array.shape)

(3, 3)


In [21]:
# Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2.

print(new_array.size)

9


**4. Operaciones Básicas:**

In [27]:
# Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.

matriz_a = np.random.randint(0,10, size=(2,2))
matriz_b = np.random.randint(0,10, size=(2,2))
suma = matriz_a + matriz_b
print(f"Matriz A: \n {matriz_a}")
print(f"Matriz B: \n {matriz_b}")
print(f"Suma : \n {suma}")

Matriz A: 
 [[9 6]
 [0 1]]
Matriz B: 
 [[2 7]
 [4 8]]
Suma : 
 [[11 13]
 [ 4  9]]


In [33]:
# Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.

matriz_a = np.random.randint(0, 10, size=(3, 2))
matriz_b = np.random.randint(0, 10, size=(2, 3))

producto = np.dot(matriz_3x2, matriz_2x3)

print(f"Matriz 3x2: \n{matriz_a}")
print(f"Matriz 2x3: \n{matriz_b}")
print(f"Producto: \n{producto}")


Matriz 3x2: 
[[6 0]
 [2 2]
 [2 2]]
Matriz 2x3: 
[[7 2 0]
 [4 5 7]]
Producto: 
[[55 77 80]
 [36 72 72]
 [56 68 72]]


In [70]:
# Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2,
matriz_a = np.random.randint(1, 10, size=(2, 2))
matriz_b = np.random.randint(1, 10, size=(2, 2))

division = matriz_a / matriz_b

print(f"Matriz A: \n {matriz_a}")
print(f"Matriz B: \n {matriz_b}")
print(f"Division : \n {division}")

Matriz A: 
 [[1 8]
 [9 9]]
Matriz B: 
 [[8 7]
 [4 6]]
Division : 
 [[0.125      1.14285714]
 [2.25       1.5       ]]


**5. Manipulación de Arrays:**

In [52]:
# Utiliza la función reshape() para convertir el vector creado en el paso 2 en una matriz de tamaño 2x3.

reshape = new_array.reshape((9,1))
print(reshape)

[[ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [47]:
# Utiliza la función flatten() para convertir la matriz creada en el paso 2 en un vector unidimensional.

flatten= new_array.flatten()
print(flatten)


[ 4  5  6  7  8  9 10 11 12]


**6. Operaciones Estadísticas:**

In [54]:
# Calcula la suma de todos los elementos de la matriz creada en el paso 2.

sum_of_elements = np.sum(new_array)
print(f"Arreglo: \n {new_array}")
print(f"La suma de todos los elementos es: {sum_of_elements}")


Arreglo: 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
La suma de todos los elementos es: 72


In [60]:
# Calcula la media de cada fila de la matriz creada en el paso 2.

media = np.mean(new_array, axis=1,)
print(f"Arreglo: \n {new_array}")
print(f"La media de cada fila es: {media}")


Arreglo: 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
La media de cada fila es: [ 5.  8. 11.]


**7. Indexación y Rebanado:**

In [61]:
# Imprime la primera fila de la matriz creada en el paso 2.

print(new_array[0])


[4 5 6]


In [64]:
# Imprime las primeras dos columnas de la matriz creada en el paso 2.

print(new_array[:, :2])

[[ 4  5]
 [ 7  8]
 [10 11]]


**8. Ejercicio Adicional:**

In [65]:
# Define una matriz de tamaño 4x4 con valores aleatorios.

matriz =np.random.rand(4,4)
print(matriz)

[[0.92734612 0.55629209 0.20975675 0.77393385]
 [0.29132039 0.85983963 0.77285769 0.09633629]
 [0.63276733 0.39484963 0.55280209 0.60761445]
 [0.94048411 0.39286936 0.24667594 0.23928693]]


In [71]:
# Encuentra el valor máximo y su posición en filas y columnas.
max_value = np.max(matriz)
max_index = np.argmax(matriz)
max_row = max_index // 4
max_col = max_index % 4

# Encuentra el valor mínimo y su posición en filas y columnas.
min_value = np.min(matriz)
min_index = np.argmin(matriz)
min_row = min_index // 4
min_col = min_index % 4

# Imprime los resultados.
print("Matriz:")
print(matriz)
print("\nValor máximo:", max_value)
print("Fila:", max_row, "Columna:", max_col)
print("\nValor mínimo:", min_value)
print("Fila:", min_row, "Columna:", min_col)


Matriz:
[[0.78831868 0.51593728 0.26846669 0.21151564]
 [0.00677973 0.46367112 0.38248523 0.56034837]
 [0.69899324 0.10836226 0.61158789 0.18010783]
 [0.82796825 0.01599738 0.39933679 0.84568685]]

Valor máximo: 0.8456868516968259
Fila: 3 Columna: 3

Valor mínimo: 0.006779729296704118
Fila: 1 Columna: 0
